name: Dit un dat
description: 
meta_description: "Something profound should be here"
twitter_username: 'eckardo'
github_username: 'eckart'

markdown: redcarpet
highlighter: pygments
logo: false
paginate: 15
baseurl: /
domain_name: 'http://eckart.github.io'
email:
#google_analytics: 'UA-XXXXXXXX-X'

exclude: ["*.ibc"]
# Details for the RSS feed generator
url:            'http://eckart.github.io'
author:         'Eckart'


